### ISSUE TITLE
upstream sent unsupported FastCGI protocol version: 6 while reading upstream

### ISSUE THREAD

**Issue by parihaaraka** [artyom-beilis/cppcms#24] opened 2017-11-24 13:36 UTC
Unable to send big response (~223kb) from cppcms via fastcgi to nginx 
cppcms: cppcms, warning: Failed to write response:system: Connection reset by peer (http_response.cpp:305)
NGINX (1.8.1): upstream sent unsupported FastCGI protocol version: 6 while reading upstream

Changing nginx buffers does not help.

the code flow is about this:
```
cln_job->http_context->response().out() << body;
cln_job->http_context->async_flush_output(
                        bind(&dispatcher_app::flush_output_handler,
                             booster::intrusive_ptr<dispatcher_app>(this),
                             std::placeholders::_1,
                             cln_job));
```
Inside flush_output_handler() i do 
```
    job->http_context->async_complete_response();
    job->http_context.reset();
```
immediately. It looks like the problem is here, but i can't find info on how to process big response.

**Comment by artyom-beilis** [comment] 2017-11-24 19:50
Have you googled this error: For example https://github.com/xplicit/HyperFastCgi/issues/55 gives interesting direction. Try to go this way.

Also what version of CppCMS do you use?

If the issue still occurs please record strace output of CppCMS process to see what exactly happens in terms of NGinx/CppCMS communication.

**Comment by parihaaraka** [comment] 2017-11-24 21:14
Hello, Artyom. Thank you for feedback. Yes, I've googled a lot, and the is not much to do I've found: busy port, "Expect:" header and buffers size. I've tried all of them (including cppcms buffers and different cppcms method sequences) without success.

cppcms info:
Repository Root: https://svn.code.sf.net/p/cppcms/code
Repository UUID: 831565cc-8e21-4ad5-8334-98019c97bd36
Revision: 2413
Node Kind: directory
Schedule: normal
Last Changed Author: artyom-beilis
Last Changed Rev: 2413
Last Changed Date: 2016-04-04 15:52:48 +0300 (Mon, 04 Apr 2016)

strace output:
https://drive.google.com/file/d/1N36gOi2dZTdIunOXgN6azeA2FtUJOZ77/view?usp=sharing

**Comment by artyom-beilis** [comment] 2017-11-24 21:49
Ok. It looks like it sends all the data but nginx closes the connection.

1. Can you check if same happens in latest cppcms from github master?
2. Can you please provide a small program that reporduces the issue with sample configuration (including NGINX one)
3. It would also be helpful if you can check if another web server like lighttpd fails as well.

**Comment by parihaaraka** [comment] 2017-11-24 21:55
i'll try to do it probably on monday :(
i'll let you know as soon as i get results
* reuploaded tracelog with -f option

**Comment by parihaaraka** [comment] 2017-11-25 12:09
lighttpd/1.4.35:
```
(mod_fastcgi.c.3054) got proc: pid: 0 socket: tcp:10.0.33.21:7788 load: 1
(mod_fastcgi.c.2562) unexpected end-of-file (perhaps the fastcgi process died): pid: 0 socket: tcp:10.0.33.21:7788
(mod_fastcgi.c.3346) response not received, request sent: 649 on socket: tcp:10.0.33.21:7788 for /pc4x4?, closing connection
(mod_fastcgi.c.1505) released proc: pid: 0 socket: tcp:10.0.33.21:7788 load: 0
```
short cppcms responses are ok

**Comment by parihaaraka** [comment] 2017-11-25 13:29
test application:
```
#include <iostream>
#include <cppcms/url_dispatcher.h>
#include <cppcms/service.h>
#include <cppcms/applications_pool.h>
#include <cppcms/json.h>
#include <cppcms/http_response.h>
#include <cppcms/http_context.h>
#include <cppcms/http_request.h>

using namespace std;
using namespace cppcms;

class dispatcher_app : public cppcms::application
{
public:
    explicit dispatcher_app(cppcms::service &s) :
        cppcms::application(s), _service(s)
    {
        dispatcher().assign(".*", &dispatcher_app::request_handler, this);
    }

    ~dispatcher_app() = default;

private:
    cppcms::service &_service;
    booster::shared_ptr<http::context> _http_context;

    void request_handler()
    {
        cout << "request from " << request().remote_addr()
             << ": " << request().getenv("REQUEST_URI") << endl;
        std::string body(1024 * 256,  'x');
        _http_context = release_context();
        _http_context->response().out() << body;
        _http_context->async_flush_output(
                    bind(&dispatcher_app::flush_output_handler,
                         booster::intrusive_ptr<dispatcher_app>(this),
                         std::placeholders::_1));
    }

    void flush_output_handler(cppcms::http::context::completion_type)
    {
        _http_context->async_complete_response();
        _http_context.reset();
        _service.shutdown();
    }
};

int main()
{
    json::value params;
    params["service"]["api"] = "fastcgi";
    params["service"]["port"] = 7788;
    params["service"]["ip"] = "0.0.0.0";
    params["service"]["worker_processes"] = 0;
    params["service"]["worker_threads"] = 0;
    params["logging"]["level"] = "debug";
    params["logging"]["stderr"] = true;
    service srv(params);

    booster::intrusive_ptr<dispatcher_app> disp = new dispatcher_app(srv);
    srv.applications_pool().mount(disp);

    cout << "started" << endl;
    srv.run();
    cout << "stopped" << endl;
    return 0;
}
```
lighttpd standard config change:
```
fastcgi.server = (
  "/test" =>
  (( "host" => "127.0.0.1",
     "port" => 7788,
     "max-procs" => 1,
     "check-local" => "disable"
  ))
)
```
nginx fcgi part of config:
```
location ~ /test/.+ {
    fastcgi_pass  127.0.0.1:7788;
    fastcgi_pass_header "X-Accel-Redirect";
    add_header Cache-Control  "max-age=0, no-cache, no-store";
    
    fastcgi_split_path_info ^(/test)(.+)$;
    fastcgi_param  PATH_INFO          $fastcgi_path_info;
    include fastcgi_params;
    fastcgi_pass_request_headers on;
}
```
curl / large response (lighttpd):
```
# curl -v http://127.0.0.1:85/test > res.txt
*   Trying 127.0.0.1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 127.0.0.1 (127.0.0.1) port 85 (#0)
> GET /test HTTP/1.1
> Host: 127.0.0.1:85
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 503 Service Not Available
< Content-Type: text/html
< Content-Length: 369
< Date: Sat, 25 Nov 2017 13:25:47 GMT
< Server: lighttpd/1.4.35
< 
{ [369 bytes data]
100   369  100   369    0     0   596k      0 --:--:-- --:--:-- --:--:--  360k
* Connection #0 to host 127.0.0.1 left intact
```
curl / small response (lighttpd):
```
# curl -v http://127.0.0.1:85/test > res.txt
*   Trying 127.0.0.1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 127.0.0.1 (127.0.0.1) port 85 (#0)
> GET /test HTTP/1.1
> Host: 127.0.0.1:85
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
< X-Powered-By: CppCMS/1.1.1
< Transfer-Encoding: chunked
< Date: Sat, 25 Nov 2017 13:27:28 GMT
< Server: lighttpd/1.4.35
< 
{ [16207 bytes data]
100 16384    0 16384    0     0  8616k      0 --:--:-- --:--:-- --:--:-- 15.6M
* Connection #0 to host 127.0.0.1 left intact
```

**Comment by artyom-beilis** [comment] 2017-11-25 19:47
Thanks... 

Reproduced. I'll try to fix it ASAP.

**Comment by parihaaraka** [comment] 2017-11-25 19:49
Thank you too! cppcms is a cool thing!

**Comment by double2li** [comment] 2017-11-27 07:39
how can cppcms support https? thanks

**Comment by artyom-beilis** [comment] 2017-11-27 07:47
Internal CppCMS server does not support HTTPS only HTTP.

It is on the road map for future version: http://cppcms.com/wikipp/en/page/cppcms_1x_tasks#HTTP.Server.improvements

You can use external server for HTTPS support via FastCGI or SCGI. Alternatively you can work behind reverse proxy with HTTP

**Comment by artyom-beilis** [comment] 2017-11-27 10:18
Fixed in master

**Comment by parihaaraka** [comment] 2017-11-27 14:43
Artyom, I beg your pardon.. is that bad:
```
"test_aio_socket" start time: Nov 27 16:51 MSK
Output:
----------------------------------------------------------
Testing buffers
Test basic io
Test get/set io_service
Test async connect
Test async connect fail
Testing Unix Sockets
Testing IPv6
Failed:system: Cannot assign requested address
<end of output>
Test time =   0.01 sec
----------------------------------------------------------
Test Failed.
```
::1:8080 is not busy

**Comment by parihaaraka** [comment] 2017-11-27 20:56
Linux xfce 4.10.0-40-generic #44~16.04.1-Ubuntu SMP Thu Nov 9 15:37:44 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
(last commit 6ac03c0fc0e0a000a399f49163429917eaa8c4dc):
```
"proto_test_async_fastcgi_unix" start time: Nov 27 23:45 MSK
Output:
----------------------------------------------------------
Asynchronous testing
Ok:fcgi keep alive first scgi_1
Ok:fcgi keep alive second scgi_1
Ok:fcgi keep alive first scgi_2
Ok:fcgi keep alive second scgi_2
Ok:fcgi keep alive first scgi_3
Ok:fcgi keep alive second scgi_3
Ok:scgi_1 normal
Ok:scgi_1 random 1
Ok:scgi_1 random 2
Ok:scgi_1 random 3
Ok:scgi_1 shortest
Ok:scgi_2 normal
Ok:scgi_2 random 1
Ok:scgi_2 random 2
Ok:scgi_2 random 3
Ok:scgi_2 shortest
Ok:scgi_3 normal
Ok:scgi_3 random 1
Ok:scgi_3 random 2
Ok:scgi_3 random 3
Ok:scgi_3 shortest
Testing big pairs
Ok:fcgi keep alive first scgi_4
Ok:fcgi keep alive second scgi_4
Ok:fcgi keep alive first scgi_5
Ok:fcgi keep alive second scgi_5
Ok:scgi_4 normal
Ok:scgi_4 random 1
Ok:scgi_4 random 2
Ok:scgi_4 random 3
Ok:scgi_4 shortest
Ok:scgi_5 normal
Ok:scgi_5 random 1
Ok:scgi_5 random 2
Ok:scgi_5 random 3
Ok:scgi_5 shortest
Testing chunked pairs
Ok:scgi_4 normal
Ok:scgi_5 normal
Testing GET_VALUES
Ok:scgi_1 normal
Testing long message
Invalid header [\1\6\0\1..\1.]
<end of output>
Test time =  13.40 sec
----------------------------------------------------------
Test Failed.
```
finally:
```
99% tests passed, 1 tests failed out of 113

Total Test time (real) = 425.70 sec

The following tests FAILED:
	 62 - proto_test_async_fastcgi_unix (Failed)
Errors while running CTest
```

**Comment by artyom-beilis** [comment] 2017-11-27 21:18
Ok I see

**Comment by artyom-beilis** [comment] 2017-11-29 12:31
Ok, hopefully now it is solved. I'll see if night tests return ok and then close it

**Comment by parihaaraka** [comment] 2017-11-29 18:21
`100% tests passed, 0 tests failed out of 113`
thanks ;)

**Closed** 2017-12-03 21:09 UTC
Labels: bug
